"""Data models for the POWERFLOW 24‑hour simulation.

The objects are deliberately lightweight and JSON‑serialisable – they are
used to hold the transient state during a run and can be persisted to a
relational DB or exported to JSON/CSV.
"""

from __future__ import annotations

import datetime as dt
from dataclasses import dataclass, field
from typing import List, Dict, Optional


@dataclass
class HouseholdState:
    """Current state of a single household at a simulation interval.

    * ``household_id`` – unique identifier, e.g. ``H001``.
    * ``is_prosumer`` – ``True`` when the household has PV (and optionally
      a battery).
    * ``demand_kwh`` – forecast demand for the interval.
    * ``solar_kwh`` – forecast solar generation for the interval (0 if not a
      prosumer).
    * ``battery_soc`` – state‑of‑charge in kWh (optional, ``None`` if no
      storage).
    * ``surplus_kwh`` – ``max(solar_kwh - demand_kwh, 0)`` after battery
      dispatch.
    * ``deficit_kwh`` – ``max(demand_kwh - solar_kwh, 0)`` after battery
      dispatch.
    """

    household_id: str
    is_prosumer: bool
    demand_kwh: float
    solar_kwh: float = 0.0
    battery_soc: Optional[float] = None
    surplus_kwh: float = 0.0
    deficit_kwh: float = 0.0

    def update_surplus_deficit(self) -> None:
        """Calculate surplus / deficit after optional battery dispatch.
        ``battery_soc`` is assumed to be already updated by the battery logic.
        """
        net = self.solar_kwh - self.demand_kwh
        if net >= 0:
            self.surplus_kwh = net
            self.deficit_kwh = 0.0
        else:
            self.surplus_kwh = 0.0
            self.deficit_kwh = -net


@dataclass
class FeederState:
    """Aggregated state for a distribution feeder at a given interval.

    * ``feeder_id`` – identifier, e.g. ``FEEDER‑A``.
    * ``capacity_mw`` – nominal capacity (MW).
    * ``headroom_mw`` – remaining capacity after applying all scheduled
      imports/exports.
    * ``congestion`` – ``True`` when headroom <= 0.
    * ``voltage_violation`` – optional flag for voltage limits (filled by the
      grid physics service).
    """

    feeder_id: str
    capacity_mw: float
    headroom_mw: float
    congestion: bool = False
    voltage_violation: bool = False

    def update_headroom(self, net_import_mw: float) -> None:
        """Update headroom after a net import/export flow.
        ``net_import_mw`` > 0 means import from grid, < 0 means export.
        """
        self.headroom_mw = self.capacity_mw - net_import_mw
        self.congestion = self.headroom_mw <= 0


@dataclass
class Order:
    """Buy or sell order generated by a household.

    * ``order_id`` – UUID string.
    * ``household_id`` – origin of the order.
    * ``feeder_id`` – feeder to which the household belongs.
    * ``type`` – ``"buy"`` or ``"sell"``.
    * ``quantity_kwh`` – amount of energy.
    * ``price_limit`` – maximum (buy) or minimum (sell) price in INR/kWh.
    * ``status`` – ``"pending"``, ``"matched"`` or ``"rejected"``.
    """

    order_id: str
    household_id: str
    feeder_id: str
    type: str
    quantity_kwh: float
    price_limit: float
    status: str = "pending"


@dataclass
class Trade:
    """Result of matching a buy and a sell order.

    * ``trade_id`` – UUID string.
    * ``buy_order_id`` / ``sell_order_id`` – linked orders.
    * ``price_kwh`` – executed price.
    * ``quantity_kwh`` – executed quantity (may be partial).
    """

    trade_id: str
    buy_order_id: str
    sell_order_id: str
    price_kwh: float
    quantity_kwh: float


@dataclass
class SimulationInterval:
    """Snapshot of the system at a single time step.

    All timestamps are stored as timezone‑aware ``datetime`` objects.
    """

    timestamp: dt.datetime
    households: List[HouseholdState] = field(default_factory=list)
    feeders: List[FeederState] = field(default_factory=list)
    orders: List[Order] = field(default_factory=list)
    trades: List[Trade] = field(default_factory=list)
    market_price_kwh: float = 0.0
    congestion_events: int = 0
    reverse_power_flow: bool = False


@dataclass
class SimulationState:
    """Container for the full 24‑hour run.

    * ``config`` – the ``SimulationConfig`` used for this run.
    * ``intervals`` – ordered list of ``SimulationInterval`` objects.
    * ``metrics`` – optional dict populated after the run.
    """

    config: "SimulationConfig"
    intervals: List[SimulationInterval] = field(default_factory=list)
    metrics: Optional[Dict[str, float]] = None
